# Generated by Django 4.1.4 on 2023-01-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='place',
            new_name='Place',
        ),
    ]
